[build]
# Use Python 3.11 for compatibility
nixpacks.version = "1.x"
builder = "NIXPACKS"

[deploy]
# Start command for the Flask app
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --log-level debug app:app"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
# Production environment
FLASK_ENV = "production"
FLASK_SKIP_DOTENV = "1"
PYTHONUNBUFFERED = "1"

# Note: Set OPENAI_API_KEY in Railway dashboard environment variables 